name: Deploy to Server

on:
  workflow_dispatch:
    # pull_request:
    #   branches: 
    #     - main
    #   types:
    #     - closed

jobs:
  Openconnect:
    runs-on: ubuntu-20.04
    steps:
    - run: apt upgrade && apt install openconnect -y
    - run: sudo openconnect --protocol=anyconnect --authgroup='UCF Students' --background secure.vpn.ucf.edu
