on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
    - run: |
        echo The PR was merged