name: Deploy to Server

on:
  - push
  # workflow_run:
  #   workflows:
  #     - "Lint Files"
  #   types: 
  #     - completed


jobs:

  openconnect: 
    runs-on: ubuntu-20.04
    steps:
    - run: sudo apt-get upgrade && sudo apt-get install openconnect -y
    - run: echo ${{ secrets.PASS }} | sudo openconnect --protocol=anyconnect --user=${{ secrets.UNAME }} --passwd-on-stdin --authgroup='UCF Students' secure.vpn.ucf.edu
