name: Deploy to Server

on:
  workflow_run:
    workflows: [Lint Files]
    types: 
      - completed


jobs:

  on-success:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
    - run: apt upgrade && apt install openconnect -y
    - run: sudo openconnect --protocol=anyconnect --authgroup='UCF Students' --background secure.vpn.ucf.edu
